# Packages are ordered alphabetically
# To install ipykernel:
#     python -m ipykernel install --user --name rl
name: relearn
channels:
- defaults
- conda-forge
- gpytorch
- pytorch
dependencies:
- botorch
- cudatoolkit=10.1
- gast==0.2.2
- ipykernel
- jupyter
- jupyter_contrib_nbextensions
- matplotlib
- numpy
- pandas
- pip
- pillow<7
- plotly >=2.2.1
- pytorch=1.4
- python=3.7
- scikit-learn
- scipy
- seaborn
- torchvision
- tqdm
- pip:
  - ax-platform
  - black
  - blackcellmagic
  - gym
  - Jinja2
  - ray
  - requests
  - stable-baselines
  - tensorflow-gpu==1.14
